MobileTeleSystems/onetl

- .github/workflows/codeql-analysis.yml
- .github/workflows/dev-release.yml
- docs/conf.py
- setup.py
This workflow pushes .dev versions of onETL to [test.pypi.org](https://test.pypi.org/project/onetl/).
.dev versions are pushed on every commit in every branch (except master), but only after successfully finished code analysis and tests (TODO), and only if push is performed to original repo (not fork).
> [DOP-3139] Add dev release workflow

- .github/workflows/test-mysql.yml
- .github/workflows/tests.yml
- requirements/tests/mysql.txt
- tests/tests_integration/tests_db_connection_integration/test_mysql_integration.py
Added workflow for MySQL tests, using Clickhouse workflow as a template.
> [DOP-3137] Add tests workflow for MySQL

- .github/workflows/test-postgres.yml
- .github/workflows/tests.yml
Added workflow for Postgres tests, using Clickhouse workflow as a template.
> [DOP-3137] Add tests workflow for Postgres

- .github/workflows/test-mssql.yml
- .github/workflows/tests.yml
- tests/tests_integration/tests_db_connection_integration/test_clickhouse_integration.py
- tests/tests_integration/tests_db_connection_integration/test_mssql_integration.py
Added workflow for MSSQL tests, using Clickhouse workflow as a template.
> [DOP-3137] Add tests workflow for MSSQL

- .github/workflows/test-core.yml
- .github/workflows/test-mongodb.yml
- .github/workflows/test-mssql.yml
- .github/workflows/test-postgres.yml
- .github/workflows/test-s3.yml
- .github/workflows/test-teradata.yml
- .github/workflows/tests.yml
- tests/tests_integration/tests_db_connection_integration/test_mongodb_integration.py
Added workflow for MongoDB tests, using Clickhouse workflow as a template.
> [DOP-3137] Add tests workflow for MongoDB

- onetl/connection/file_connection/s3.py
- tests/tests_integration/tests_file_connection_integration/test_s3_integration.py
Previously S3.listdir and S3.walk returned nothing for "/" input. Fixed.
> [DOP-4782] Fix S3.walk empty result for /

- docs/changelog/next_release/79.feature.rst
- onetl/connection/db_connection/kafka/connection.py
- onetl/connection/db_connection/kafka/ikafka_protocol.py
- onetl/connection/db_connection/kafka/kafka_auth.py
- onetl/connection/db_connection/kafka/kafka_basic_auth.py
- onetl/connection/db_connection/kafka/kafka_kerberos_auth.py
- onetl/connection/db_connection/kafka/kafka_plaintext_protocol.py
- onetl/connection/db_connection/kafka/kafka_protocol.py
- tests/tests_unit/tests_db_connection_unit/test_kafka_unit.py
Implement KafkaProtocol and tests for it
> [DOP-7289] Implement KafkaProtocol

- onetl/connection/db_connection/kafka/connection.py
- tests/tests_unit/test_db/test_db_reader_unit/test_kafka_reader_unit.py
- tests/tests_unit/tests_strategy_unit/test_strategy_unit.py
- add `get_df_schema` for Kafka connection
- add unit test to check Kafka doesn't work with batch strategies
> [DOP-7820] - add get_df_schema for Kafka

- onetl/connection/db_connection/kafka/connection.py
- onetl/connection/db_connection/kafka/slots.py
- tests/tests_integration/tests_db_connection_integration/test_kafka_integration.py
- tests/tests_unit/tests_db_connection_unit/test_kafka_unit.py
- add `Kafka.Slots` to validate connection attributes with hooks
- add unit and integration tests for `Kafka.Slots` hooks
- add documentation
> [DOP-7932] - add Kafka.Slots

- onetl/hwm/store/hwm_class_registry.py
- requirements/core.txt
- tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_clickhouse.py
- tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_greenplum.py
- tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_hive.py
- tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_mongodb.py
- tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_mssql.py
- tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_mysql.py
- tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_oracle.py
- tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_postgres.py
Drop custom DecimalHWM class, replace it with ColumnIntHWM. See https://github.com/MobileTeleSystems/etl-entities/pull/58
> [DOP-9787] Drop DecimalHWM type

- .github/workflows/codeql-analysis.yml
- .github/workflows/data/mongodb/matrix.yml
- docs/changelog/next_release/161.feature.rst
- docs/changelog/next_release/187.feature.rst
- onetl/connection/db_connection/mongodb/connection.py
- onetl/file/format/excel.py
- requirements/tests/spark-3.3.3.txt
- requirements/tests/spark-3.4.2.txt
- tests/tests_unit/test_file/test_format_unit/test_excel_unit.py
* Update spark-excel to [0.20.3](https://github.com/crealytics/spark-excel/releases)
* Update Spark 3.4.1 to [3.4.2](https://spark.apache.org/releases/spark-release-3-4-2.html)
> [DOP-9653] Update Excel package version to 0.20.3

- onetl/connection/db_connection/kafka/connection.py
- add `Kafka.get_min_max_values(...)` method, to fetch min, max offsets values accordingly to passed `Window` 
> [DOP-2348] - add get_min_max_values in Kafka connection

- CONTRIBUTING.rst
- docs/changelog/NEXT_RELEASE.rst
- docs/changelog/index.rst
* Remove comments from `NEXT_RELEASE.rst`. They are just an old copy of release process documentation.
* Remove `NEXT_RELEASE` section from changelog index, this file is always empty.
* Improve release process documentation
> [DOP-13156] Update release instuction

- docs/changelog/next_release/229.feature.rst
- docs/changelog/next_release/229.improvement.rst
- docs/connection/db_connection/clickhouse/read.rst
- docs/connection/db_connection/clickhouse/types.rst
- docs/connection/db_connection/clickhouse/write.rst
- docs/connection/db_connection/postgres/execute.rst
- docs/connection/db_connection/postgres/index.rst
- docs/connection/db_connection/postgres/prerequisites.rst
- docs/connection/db_connection/postgres/read.rst
- docs/connection/db_connection/postgres/sql.rst
- docs/connection/db_connection/postgres/types.rst
- docs/connection/db_connection/postgres/write.rst
- onetl/connection/db_connection/greenplum/connection.py
- onetl/connection/db_connection/postgres/connection.py
- tests/tests_unit/tests_db_connection_unit/test_jdbc_options_unit.py
- tests/tests_unit/tests_db_connection_unit/test_postgres_unit.py
* Added [separated page](https://onetl--229.org.readthedocs.build/en/229/connection/db_connection/postgres/types.html) with Postgres <-> Spark types mapping, and recommendations related to type casts.
* Added [separated page](https://onetl--229.org.readthedocs.build/en/229/connection/db_connection/postgres/prerequisites.html) with Postgres prerequisites like post number and grants.
* Split documentation of [DBReader](https://onetl--229.org.readthedocs.build/en/229/connection/db_connection/postgres/read.html) and [Postgres.sql](https://onetl--229.org.readthedocs.build/en/229/connection/db_connection/postgres/sql.html) to different pages
* Added more examples to reading & writing data to Postgres, and using `fetch` and `execute` methods.
(see …
> [DOP-13253] Add Postgres types & prerequisites documentation

- docs/changelog/next_release/234.improvement.rst
- docs/connection/db_connection/mysql/execute.rst
- docs/connection/db_connection/mysql/index.rst
- docs/connection/db_connection/mysql/prerequisites.rst
- docs/connection/db_connection/mysql/read.rst
- docs/connection/db_connection/mysql/sql.rst
- docs/connection/db_connection/mysql/types.rst
- docs/connection/db_connection/mysql/write.rst
- onetl/connection/db_connection/mysql/connection.py
* Added [separated page](https://onetl--234.org.readthedocs.build/en/234/connection/db_connection/mysql/types.html) with MySQL <-> Spark types mapping, and recommendations related to type casts.
* Added [separated page](https://onetl--234.org.readthedocs.build/en/234/connection/db_connection/mysql/prerequisites.html) with MySQL prerequisites like port number and grants.
* Split documentation of [DBReader](https://onetl--234.org.readthedocs.build/en/234/connection/db_connection/mysql/read.html) and [MySQL.sql](https://onetl--234.org.readthedocs.build/en/234/connection/db_connection/mysql/sql.html) to different pages
* Added more examples to reading & writing data to MySQL, and using `fetch` and `execute` methods.
(see [CONTRIBUTING.rst](https://github.com/MobileTeleSystems/onetl/blob/develo …
> [DOP-13252] Improve MySQL documentation

- docs/changelog/next_release/211.improvement.rst
- docs/changelog/next_release/228.improvement.rst
- docs/changelog/next_release/229.improvement.rst
- docs/changelog/next_release/233.improvement.rst
- docs/connection/db_connection/clickhouse/execute.rst
- docs/connection/db_connection/clickhouse/prerequisites.rst
- docs/connection/db_connection/clickhouse/sql.rst
- docs/connection/db_connection/clickhouse/types.rst
- docs/connection/db_connection/greenplum/execute.rst
- docs/connection/db_connection/greenplum/types.rst
- docs/connection/db_connection/oracle/execute.rst
- docs/connection/db_connection/oracle/index.rst
- docs/connection/db_connection/oracle/prerequisites.rst
- docs/connection/db_connection/oracle/read.rst
- docs/connection/db_connection/oracle/sql.rst
- docs/connection/db_connection/oracle/types.rst
- docs/connection/db_connection/oracle/write.rst
- docs/connection/db_connection/postgres/execute.rst
- docs/connection/db_connection/postgres/prerequisites.rst
- docs/connection/db_connection/postgres/read.rst
- docs/connection/db_connection/postgres/types.rst
- docs/connection/db_connection/postgres/write.rst
- onetl/connection/db_connection/oracle/connection.py
* Added [separated page](https://onetl--233.org.readthedocs.build/en/233/connection/db_connection/oracle/types.html) with Oracle <-> Spark types mapping, and recommendations related to type casts.
* Added [separated page](https://onetl--233.org.readthedocs.build/en/233/connection/db_connection/oracle/prerequisites.html) with Oracle prerequisites like port number and grants.
* Split documentation of [DBReader](https://onetl--233.org.readthedocs.build/en/233/connection/db_connection/oracle/read.html) and [Oracle.sql](https://onetl--233.org.readthedocs.build/en/233/connection/db_connection/oracle/sql.html) to different pages
* Added more examples to reading & writing data to Oracle, and using `fetch` and `execute` methods.
* Also updated a bit documentation of other DB connections, like …
> [DOP-13252] Improve Oracle documentation

- docs/changelog/next_release/236.improvement.rst
- docs/connection/db_connection/mongodb/index.rst
- docs/connection/db_connection/mongodb/pipeline.rst
- docs/connection/db_connection/mongodb/prerequisites.rst
- docs/connection/db_connection/mongodb/read.rst
- docs/connection/db_connection/mongodb/types.rst
- docs/connection/db_connection/mongodb/write.rst
- onetl/connection/db_connection/mongodb/connection.py
- onetl/connection/db_connection/mongodb/options.py
Sync MongoDB documentation structure and content with other databases, like Clickhouse, Oracle, Postgres - see #233, #234, #229.
See https://onetl--236.org.readthedocs.build/en/236/connection/db_connection/mongodb/index.html
> [DOP-13681] Improve MongoDB documentation

- docs/conf.py
- onetl/_util/hadoop.py
- onetl/_util/scala.py
- onetl/_util/spark.py
- onetl/_util/version.py
- onetl/connection/db_connection/greenplum/connection.py
- onetl/connection/db_connection/jdbc_mixin/connection.py
- onetl/connection/db_connection/kafka/connection.py
- onetl/connection/db_connection/mongodb/connection.py
- onetl/connection/db_connection/mssql/connection.py
- onetl/connection/db_connection/oracle/connection.py
- onetl/connection/file_df_connection/spark_s3/connection.py
- onetl/file/format/avro.py
- onetl/file/format/excel.py
- onetl/file/format/xml.py
- tests/fixtures/spark.py
- tests/tests_integration/test_file_format_integration/test_avro_integration.py
- tests/tests_integration/test_file_format_integration/test_csv_integration.py
- tests/tests_integration/test_file_format_integration/test_excel_integration.py
- tests/tests_integration/test_file_format_integration/test_xml_integration.py
- tests/tests_unit/test_file/test_format_unit/test_avro_unit.py
- tests/tests_unit/test_file/test_format_unit/test_excel_unit.py
- tests/tests_unit/test_file/test_format_unit/test_xml_unit.py
- tests/tests_unit/tests_db_connection_unit/test_greenplum_unit.py
- tests/tests_unit/tests_db_connection_unit/test_kafka_unit.py
- tests/tests_unit/tests_db_connection_unit/test_mongodb_unit.py
- tests/tests_unit/tests_file_df_connection_unit/test_spark_s3_unit.py
- update `Version`  from `onetl._util.version` to store raw string version, as some packages may include string data, like `1.2.3-patch4`.
- update following tests
> [DOP-14546] - update Version to store raw str version

- docs/changelog/next_release/259.feature.rst
- onetl/file/format/xml.py
- tests/tests_unit/test_file/test_format_unit/test_xml_unit.py
Update XML package version from 0.17.0 to 0.18.0: https://github.com/databricks/spark-xml/releases/tag/v0.18.0
> [DOP-15511] Update XML package to 0.18.0

- .github/workflows/test-greenplum.yml
- CONTRIBUTING.rst
- onetl/_util/version.py
- onetl/connection/db_connection/greenplum/connection.py
- onetl/connection/db_connection/kafka/connection.py
- onetl/connection/file_df_connection/spark_s3/connection.py
- onetl/file/format/avro.py
- onetl/file/format/excel.py
- onetl/file/format/xml.py
- pytest.ini
- tests/fixtures/spark.py
- tests/tests_integration/test_file_format_integration/test_avro_integration.py
- tests/tests_integration/test_file_format_integration/test_csv_integration.py
- tests/tests_integration/test_file_format_integration/test_excel_integration.py
- tests/tests_integration/test_file_format_integration/test_json_integration.py
- tests/tests_integration/test_file_format_integration/test_jsonline_integration.py
- tests/tests_integration/test_file_format_integration/test_orc_integration.py
- tests/tests_integration/test_file_format_integration/test_parquet_integration.py
- tests/tests_integration/test_file_format_integration/test_xml_integration.py
Do not fetch Spark packages which are not used by selected tests (using `pytest -k` or `pytest -m`). This should improve Spark startup time a bit.
> [DOP-15512] Download only packages required by tests

- docs/changelog/next_release/249.breaking.rst
- onetl/connection/db_connection/clickhouse/connection.py
- tests/fixtures/spark.py
- tests/tests_unit/tests_db_connection_unit/test_clickhouse_unit.py
Update Clickhouse package to latest version:
https://github.com/ClickHouse/clickhouse-java/releases
> [DOP-13855] Update Clickhouse package to 0.6.0-patch4

- docs/changelog/next_release/280.improvement.rst
- docs/connection/db_connection/clickhouse/prerequisites.rst
- docs/connection/db_connection/clickhouse/types.rst
- docs/connection/db_connection/kafka/prerequisites.rst
- docs/connection/db_connection/postgres/types.rst
- docs/file/file_downloader/result.rst
- docs/file/file_mover/result.rst
- docs/file/file_uploader/result.rst
New Clickhouse driver can autodiscover cluster nodes, and choose any of nodes while establishing new connection. Add note about enabling this feature to [Prerequisites](https://onetl--280.org.readthedocs.build/en/280/connection/db_connection/clickhouse/prerequisites.html) page.
Also add few small fixes to [Types](https://onetl--280.org.readthedocs.build/en/280/connection/db_connection/clickhouse/types.html) page.
> [DOP-13900] Add note about connecting to Clickhouse cluster

- docs/changelog/next_release/279.improvement.rst
- docs/connection/file_df_connection/spark_hdfs/index.rst
- docs/connection/file_df_connection/spark_hdfs/prerequisites.rst
- docs/connection/file_df_connection/spark_s3/index.rst
- docs/connection/file_df_connection/spark_s3/prerequisites.rst
- docs/connection/file_df_connection/spark_s3/troubleshooting.rst
- onetl/connection/file_df_connection/spark_hdfs/connection.py
- onetl/connection/file_df_connection/spark_local_fs.py
- onetl/connection/file_df_connection/spark_s3/connection.py
Add Prerequisites section to [SparkHDFS](https://onetl--279.org.readthedocs.build/en/279/connection/file_df_connection/spark_hdfs/prerequisites.html) and [SparkS3](https://onetl--279.org.readthedocs.build/en/279/connection/file_df_connection/spark_s3/prerequisites.html) documentation.
> [DOP-14042] Improve SparkHDFS and SparkS3 documentation

- .github/workflows/data/mysql/matrix.yml
- docs/changelog/next_release/253.feature.rst
- docs/connection/db_connection/mysql/prerequisites.rst
- onetl/connection/db_connection/mysql/connection.py
- tests/tests_unit/tests_db_connection_unit/test_mysql_unit.py
MySQL package recently updated from 8.3.0 to 8.4.0. Use the latest version.
> [DOP-13851] Update MySQL package to 8.4.0

- docs/changelog/next_release/252.feature.rst
- onetl/connection/db_connection/oracle/connection.py
- tests/tests_unit/tests_db_connection_unit/test_oracle_unit.py
Oracle package recently updated from 23.3.0.0.23.09 to 23.4.0.24.05. Use the latest version.
> [DOP-13850] Update Oracle package to 23.4.0.24.05

- docs/connection/db_connection/clickhouse/types.rst
- small clickhouse docs update
> Update clickhouse docs

- docs/changelog/next_release/344.doc.rst
- onetl/connection/db_connection/hive/connection.py
- onetl/connection/db_connection/kafka/connection.py
- onetl/connection/db_connection/mssql/connection.py
- onetl/connection/file_connection/hdfs/connection.py
- onetl/connection/file_df_connection/spark_hdfs/connection.py
- onetl/connection/file_df_connection/spark_s3/connection.py
- onetl/db/db_reader/db_reader.py
- onetl/db/db_writer/db_writer.py
- onetl/file/file_df_reader/file_df_reader.py
- onetl/file/file_df_writer/file_df_writer.py
- onetl/file/file_downloader/file_downloader.py
- onetl/file/file_mover/file_mover.py
- onetl/file/file_uploader/file_uploader.py
- onetl/hwm/store/yaml_hwm_store.py
- onetl/strategy/incremental_strategy.py
- onetl/strategy/snapshot_strategy.py
Before:
https://onetl.readthedocs.io/en/latest/
After:
https://onetl--344.org.readthedocs.build/en/344/
Most of changes is just additional indentation in docstrings.
> [DOP-23982] Use tabs for complex code examples

- docs/changelog/next_release/382.breaking.rst
- onetl/file/format/excel.py
- tests/fixtures/spark.py
- tests/tests_unit/test_file/test_format_unit/test_excel_unit.py
Old package haven't received updates for a long time.
> Update Excel package

- .github/workflows/test-hive-and-iceberg.yml
- docs/changelog/next_release/397.feature.rst
- onetl/connection/db_connection/iceberg/catalog/__init__.py
- onetl/connection/db_connection/iceberg/catalog/base.py
- onetl/connection/db_connection/iceberg/catalog/filesystem.py
- onetl/connection/db_connection/iceberg/catalog/rest.py
- onetl/connection/db_connection/iceberg/connection.py
- onetl/connection/db_connection/iceberg/warehouse/__init__.py
- onetl/connection/db_connection/iceberg/warehouse/base.py
- onetl/connection/db_connection/iceberg/warehouse/filesystem.py
- onetl/file/file_df_reader/file_df_reader.py
- onetl/file/file_df_writer/file_df_writer.py
- tests/fixtures/processing/fixtures.py
- tests/tests_integration/tests_core_integration/tests_db_reader_integration/test_iceberg_reader_integration.py
- tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_iceberg_writer_integration.py
- tests/tests_integration/tests_db_connection_integration/test_iceberg_integration.py
- tests/tests_unit/test_db/test_db_reader_unit/test_iceberg_reader.py
- tests/tests_unit/test_db/test_db_writer_unit/test_iceberg_writer_unit.py
- tests/tests_unit/tests_db_connection_unit/test_iceberg_unit.py
Added ``IcebergFilesystemCatalog``, ``IcebergFilesystemWarehouse`` classes to improve Iceberg UX.
> [DOP-28372] Implement Iceberg Filesystem Catalog & Warehouse
