.github/workflows/release.yml

This workflow pushes release versions of onETL to [pypi.org](https://pypi.org/).
Unlike .dev versions workflow (#4), releases are build and pushed only while pushing tags (not commits), and no wait for code analysis is performed (to speed up the release process).

[DOP-3140] Add release workflow

---

README.rst
docs/conf.py
docs/db_connection/index.rst
docs/db_connection/mongodb.rst
docs/index.rst
docs/static/logo.svg
docs/static/logo_wide.svg
onetl/core/db_reader/db_reader.py

- Add onETL small and wide logo images
- Add wide logo to Readme & documentation main page
- Add small logo to sidebar
https://onetl--7.org.readthedocs.build/en/7
- Rearranged sidebar items - Installation, Quick start & Concepts are on top, Development at the bottom.
- Removed links to connectors from Readme, they are valid only in ReadTheDocs, but not in the repo

[DOP-4140] Add logo

---

.github/workflows/test-teradata.yml
.github/workflows/tests.yml
conftest.py
onetl/connection/db_connection/teradata.py
tests/tests_integration/tests_db_connection_integration/test_teradata_integration.py
tests/tests_unit/tests_db_connection_unit/test_teradata_unit.py

Added workflow for Teradata tests, using Clickhouse workflow as a template.
Because there is no public Teradata docker image, integration tests are mocked, and test check only that JDBC driver can be downloaded and imported to Spark session.
Also Teradata [published JDBC driver to Maven](https://mvnrepository.com/artifact/com.teradata.jdbc/terajdbc), so I've changed `Teradata.package` value.

[DOP-3137] Add tests workflow for Teradata

---

.github/workflows/test-hive.yml
.github/workflows/tests.yml
requirements/tests/spark-3.2.0.txt
requirements/tests/spark-3.3.2.txt
setup.cfg
tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_hive_writer_integration.py
tests/tests_integration/tests_db_connection_integration/test_hive_integration.py

Added CI workflow for Hive tests.
Previously tests were run only with Spark 2.4.8. In Spark 3 some system columns in `SHOW DATABASES` and `SHOW TABLES` responses were renamed, so I've added a condition to tests.
I've also discovered that PySpark 3.3.2 was not fully compatible with NumPy 1.24+ (type `np.bool` was removed, but PySpark used it in one internal check), so I've restricted NumPy version in requirements. PySpark 3.4.0 has full support of NumPy 1.24, but a few fixes should be made to onETL to support it.

[DOP-3137] Add tests workflow for Hive

---

.github/workflows/tests.yml
README.rst
conftest.py
onetl/base/base_db_connection.py
onetl/connection/__init__.py
onetl/connection/db_connection/db_connection.py
onetl/connection/db_connection/mongodb.py
setup.cfg
tests/tests_integration/tests_db_connection_integration/test_mongodb_integration.py
tests/tests_unit/tests_db_connection_unit/test_mongodb_unit.py

Upgrade MongoDB connection from v2-3 to v10.
Minimal supported Spark version for MongoDB is now 3.2.x.
Also:
* Refactored several methods in `MongoDB.Dialect` - now there is only one method for prepairing `pipeline` dict/list and for converting it to string (using just `json.dumps`, it is already compatible with MongoDB pipeline syntax.
* Refactored `Dialect._merge_conditions` - now it converts list of WHERE condition to one condition, checks for `None` and empty list were moved to other method.
* Fixed getting min/max values of HWM in aggregation pipeline - new connector version returns dataframe with the save order of columns that were passed into pipeline, getting column by index was broken, using names instead.

[DOP-4663] Update MongoDB connector to v10

---

onetl/base/contains_get_df_schema.py
onetl/connection/db_connection/db_connection.py
onetl/connection/db_connection/dialect_mixins/__init__.py
onetl/connection/db_connection/dialect_mixins/support_hwm_expression_str.py
onetl/connection/db_connection/greenplum.py
onetl/connection/db_connection/hive.py
onetl/connection/db_connection/jdbc_connection.py
onetl/connection/db_connection/postgres.py

Default `validate_hwm_expression` implementation is moved to a separated mixin, which is imported only in DBConnection children.
Other validators (table, where, hint, etc) were already implemented as mixins. MongoDB already had `validate_hwm_expression` implementation using a mixin.

[DOP-4663] Move default validate_hwm_expression to a mixin

---

onetl/_internal.py
onetl/connection/db_connection/greenplum.py
onetl/connection/db_connection/hive.py
onetl/connection/db_connection/jdbc_connection.py
onetl/connection/db_connection/jdbc_mixin.py
onetl/connection/db_connection/mongodb.py
onetl/connection/db_connection/oracle.py
onetl/core/db_reader/db_reader.py
onetl/core/db_writer/db_writer.py
onetl/core/file_downloader/file_downloader.py
onetl/core/file_uploader/file_uploader.py
onetl/log.py

1. Implemented new logging functions (internal use only):
* `log_lines` - prints already formatter multiline string to logs. Replaces `log_with_indent("%s", ...)`
* `log_options` - prints options dict content in the following syntax:
```python
options = {
'some': 'value',
'another': 123,
}
```
Replaces ad-hoc implementations in several classes.
Note: previous logging format was:
```
options:
some = 'value'
another = 123
```
But this is not a valid Python expression, so copying this value from logs required manual changes before it can be used in code.
* `log_json` - prints to logs any value which can be converted to JSON, with proper indentation. Used mostly for printing MongoDB pipeline values.
For example, previously DBReader logs were formatted as follows:
```python
table = …
```

[DOP-4663] Improve internal logging functions

---

onetl/connection/db_connection/mongodb.py
onetl/connection/db_connection/mssql.py
onetl/connection/db_connection/mysql.py
onetl/connection/db_connection/oracle.py
onetl/connection/db_connection/postgres.py
tests/tests_unit/tests_db_connection_unit/test_mssql_unit.py
tests/tests_unit/tests_db_connection_unit/test_mysql_unit.py
tests/tests_unit/tests_db_connection_unit/test_oracle_unit.py
tests/tests_unit/tests_db_connection_unit/test_postgres_unit.py

* MSSQL `10.2.1.jre8` -> `12.2.0.jre8` (breaking)
* MySQL `8.0.30` -> `8.0.33`. Also package was renamed to `com.mysql:mysql-connector-j`
* Oracle `21.6.0.0.1` -> `23.2.0.0`
* Postgres `42.4.0` -> `42.6.0`

[DOP-4780] Update JDBC drivers to latest

---

onetl/log.py

Fixed format string used in `onetl.log.setup_logging`

[DOP-5595] Fix setup_logging format

---

onetl/base/supports_rename_dir.py
onetl/connection/file_connection/ftp.py
onetl/connection/file_connection/hdfs.py
onetl/connection/file_connection/mixins/__init__.py
onetl/connection/file_connection/mixins/rename_dir_mixin.py
onetl/connection/file_connection/sftp.py
onetl/connection/file_connection/webdav.py
onetl/exception.py
tests/tests_integration/tests_file_connection_integration/test_file_connection_common_integration.py

* Added mixin `RenameDirMixin`. It contains `rename_dir` method implementation and `_rename_dir` abstract method which should be implemented by inherited class (usually just the same as `_rename_file`).
* Added corresponding protocol `SupportRenameDir`
* Added new exception type `DirectoryAlreadyExists` which is raised if someone tries to use some existing directory name as target name and if `replace=False`
* Added this mixin to FTP, FTPS, HDFS and SFTP. S3 does not have directories and corresponding method in client. That's why this method not in the `BaseFileConnection` interface
* Added test for new method with all parameter combinations

[DOP-5429] Add rename_dir method

---

docs/file_connection/ftp.rst
docs/file_connection/ftps.rst
docs/file_connection/hdfs.rst
docs/file_connection/s3.rst
docs/file_connection/sftp.rst
docs/file_connection/webdav.rst
onetl/base/base_connection.py
onetl/base/base_db_connection.py
onetl/base/base_file_connection.py
onetl/connection/file_connection/file_connection.py
onetl/exception.py

* Added documentation for all public methods of `BaseFileConnection` (except `read*` and `write*`). See https://onetl--39.org.readthedocs.build/en/39/file_connection/ftp.html
* Updated documentation of `BaseConnection.check()`
* Replaced `RuntimeError` in `download_file`/`upload_file` with new `FileSizeMismatchError`
* Updated `remove_file`/`remove_dir` to return boolean which indicates whether file/dir were present before method call or not.
* Moved `resolve_dir(...)` at the top of `list_dir`/`walk` to raise exception if path is missing or wrong type as soon as possible.

[DOP-5431] Add docstrings to FileConnection methods

---

docs/file_filter/regexp.rst
docs/file_limit/base.rst
docs/file_limit/index.rst
docs/file_limit/limits_reached.rst
docs/file_limit/limits_stop_at.rst
docs/file_limit/max_files_count.rst
docs/file_limit/reset_limits.rst
docs/index.rst
onetl/base/base_file_filter.py
onetl/base/base_file_limit.py
onetl/connection/file_connection/file_connection.py
onetl/core/file_filter/file_filter.py
onetl/core/file_limit/file_limit.py
onetl/file/filter/match_all_filters.py
onetl/file/limit/__init__.py
onetl/file/limit/limits_reached.py
onetl/file/limit/limits_stop_at.py
onetl/file/limit/max_files_count.py
onetl/file/limit/reset_limits.py
requirements/core.txt
requirements/dev.txt
tests/tests_integration/tests_core_integration/test_file_downloader_integration.py
tests/tests_integration/tests_core_integration/test_file_mover_integration.py
tests/tests_unit/test_file/test_filter/test_match_all_filters.py
tests/tests_unit/test_file/test_limit/test_limits_are_reached.py
tests/tests_unit/test_file/test_limit/test_limits_stop_at.py
tests/tests_unit/test_file/test_limit/test_max_files_count.py
tests/tests_unit/test_file/test_limit/test_reset_limits.py
tests/tests_unit/tests_core_unit/test_file_limit_unit.py

- Added new `onetl.file.limit` module
- Replaced old class `FileLimit(count_limit=10)` class with `MaxFilesCount(10)`, placed new class to new module, added documentation & unit tests.
- Moved `limits_reached` to new module, renamed to `limits_stop_at`, to show that it checks a specific path against limits, added unit tests & documentation.
- Added new functions `limits_reached` and `reset_limits` which previously were a part of `FileConnection.list_dir` and `.walk`. They can help other developers to implement new modules in the future. Documented and tested them as well.
- Added documentation for `BaseFileLimit`
- Changed a bit the behavior of `BaseFileLimit.reset()` method - now the return value is used as a new limit, so it now depends on developer, should it resett a limit object …

[DOP-5632] Split FileLimit to separate limits

---

.github/workflows/data/s3/matrix.yml
.github/workflows/tests.yml
docs/changelog/next_release/58.bugfix.rst
onetl/connection/file_connection/s3.py

Fix S3.list_dir('/') returned empty list on latest Minio version. Fixed.

[DOP-7104] Fix S3.list_dir('/') returns empty list on latest Minio version

---

CONTRIBUTING.rst
docs/changelog/next_release/57.feature.rst
docs/changelog/next_release/57.improvement.1.rst
docs/changelog/next_release/57.improvement.2.rst
docs/file/file_downloader/file_downloader.rst
docs/file/file_mover/file_mover.rst
docs/file/file_uploader/file_uploader.rst
onetl/connection/file_connection/file_connection.py
onetl/connection/file_connection/ftp.py
onetl/connection/file_connection/hdfs.py
onetl/connection/file_connection/s3.py
onetl/connection/file_connection/sftp.py
onetl/connection/file_connection/webdav.py
onetl/file/file_downloader/file_downloader.py
onetl/file/file_mover/file_mover.py
onetl/file/file_uploader/file_uploader.py
onetl/log.py
tests/tests_integration/tests_core_integration/test_file_downloader_integration.py
tests/tests_integration/tests_core_integration/test_file_mover_integration.py
tests/tests_integration/tests_core_integration/test_file_uploader_integration.py

Uploading/downloading/moving files one by one maybe OK for small number of files, but definitely not for many. For example, uploading 1k files to HDFS takes about 13 minutes - namenode ensures that file blocks are replicated to proper number of data nodes, and responses to client only after that, and the rest of files are waiting for that.
All these operations are IO-bound tasks, so Python releases GIL, and we can use threads to run them in parallel.
That was changed:
* Internal implementation of `FileMover`/`FileDownloader`/`FileUploader` was enhanced to use `ThreadPoolExecutor` for parallel file operations.
* `FileMover`.`Options` / `FileDownloader`.`Options` / `FileUploader`.`Options` classes got new option `workers: int` which can be set by user to switch between plain old `for` loop …

[DOP-7051] Support parallel operations in file classes

---

.github/workflows/changelog.yml
docs/changelog/README.rst

Adding `ci:skip-changelog` disables changelog check step.

[DOP-7206] Allow to skip changelog CI check

---

docker/Dockerfile
docs/changelog/next_release/63.feature.rst
onetl/connection/db_connection/kafka.py
setup.cfg
tests/tests_integration/tests_db_connection_integration/test_kafka_integration.py
tests/tests_unit/tests_db_connection_unit/test_kafka_unit.py

The class must have a private method for generating a JAAS config that Kafka uses for authorization.
DOP-2329

[DOP-2329] Generate config for authorization in Kafka

---

docs/file/file_filters/base.rst
docs/file/file_formats/base.rst
docs/file/file_formats/csv.rst
docs/file/file_formats/index.rst
docs/file/index.rst
onetl/base/base_file_format.py
onetl/connection/db_connection/mongodb.py
onetl/file/format/__init__.py
onetl/file/format/csv.py
onetl/file/format/file_format.py
onetl/impl/generic_options.py
tests/tests_unit/test_file/test_format_unit/test_csv_unit.py
tests/tests_unit/test_file/test_format_unit/test_file_format_unit.py

* Added `CSV` file format class and related documentation & unit tests
* Small fix of typing of `GenericOptions.parse` method
If was previously planned to implement nested classes:
* `CSV.Reading(delimiter=',', inferSchema=True)`
* `CSV.Writing(delimiter=',', compression='gzip')`
But all implementations I've tried were messy or quite tricky to make working as expected.
So instead I've merged all options to just one class. We don't do anything with input options, they are just passed to Spark as-is, and there is no actual reason to make them separated to 2 classes.
Also I've added several default options just to class instead of `known_options` to improve developer experience - IDE should suggest attribute names, default values will be printed to logs, etc.
(see …

[DOP-6705] Add CSV file format

---

.readthedocs.yml
requirements/docs.txt

`autodoc-pydantic` 2.0.0 [released](https://github.com/mansenfranzen/autodoc_pydantic/blob/main/changelog.rst) few days ago, causing generating [empty documentation](https://onetl.readthedocs.io/en/latest/connection/file_df_connection/spark_local_fs.html) on pydantic models (almost all classes in onETL):
[Fixed](https://onetl--99.org.readthedocs.build/en/99/connection/file_df_connection/spark_local_fs.html)
Also updated ReadTheDocs config to use latest Ubuntu and Python versions, removing restrictions from `urllib` version.

[DOP-7895] Fix building documentation

---

docs/changelog/next_release/103.breaking.rst
docs/connection/db_connection/hive.rst
docs/connection/file_connection/hdfs.rst
onetl/connection/db_connection/hive.py
onetl/connection/file_connection/hdfs.py
tests/tests_integration/tests_file_connection_integration/test_hdfs_file_connection_integration.py
tests/tests_unit/tests_db_connection_unit/test_hive_unit.py
tests/tests_unit/tests_file_connection_unit/test_hdfs_unit.py

Renamed classes according PEP-8:
* `HDFS.slots` -> `HDFS.Slots`
* `Hive.slots` -> `Hive.Slots`
Old names are left intact to keep backward compatibility.

[DOP-7933] Rename HDFS.slots to HDFS.Slots

---

onetl/db/db_writer/db_writer.py
onetl/file/file_writer/file_writer.py
tests/tests_integration/tests_core_integration/test_file_writer_integration/test_common_file_writer_integration.py
tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_common_db_writer_integration.py

- restrict spark streaming dataframe in `DBWriter` and `FileWriter` `.run()` method
- add integration tests
- updated documentation

[DOP-7983] - restrict streaming df in run method

---

.gitignore
onetl/_util/file.py
onetl/connection/db_connection/kafka/connection.py
onetl/connection/db_connection/kafka/extra.py
onetl/connection/db_connection/kafka/kafka_auth.py
onetl/connection/db_connection/kafka/kafka_basic_auth.py
onetl/connection/db_connection/kafka/kafka_kerberos_auth.py
onetl/connection/db_connection/kafka/kafka_plaintext_protocol.py
onetl/connection/db_connection/kafka/kafka_protocol.py
onetl/connection/db_connection/kafka/options.py
onetl/connection/kerberos_helpers.py
tests/fixtures/create_keytab.py
tests/tests_integration/test_file_format_integration/test_csv_integration.py
tests/tests_integration/tests_db_connection_integration/test_kafka_integration.py
tests/tests_unit/test_file/test_file_writer_unit.py
tests/tests_unit/test_file/test_format_unit/test_avro_unit.py
tests/tests_unit/test_file/test_format_unit/test_csv_unit.py
tests/tests_unit/test_file/test_format_unit/test_file_format_unit.py
tests/tests_unit/test_file/test_format_unit/test_json_unit.py
tests/tests_unit/test_file/test_format_unit/test_jsonline_unit.py
tests/tests_unit/test_file/test_format_unit/test_orc_unit.py
tests/tests_unit/test_file/test_format_unit/test_parquet_unit.py
tests/tests_unit/tests_db_connection_unit/test_db_options_unit.py
tests/tests_unit/tests_db_connection_unit/test_greenplum_unit.py
tests/tests_unit/tests_db_connection_unit/test_jdbc_options_unit.py
tests/tests_unit/tests_db_connection_unit/test_kafka_unit.py

1. Added `Kafka.close()` method. It calls `kafka.protocol.cleanup()` and `kafka.auth.cleanup()` methods, allowing to delete temporary objects and files created by auth & protocol implementations.
2. Implemented `KafkaKerberosAuth.cleanup()` method - if it copies keytab file to current directory, and file still exist, it will be deleted. To prevent deleting source keytab (e.g. `Kafka.KerberosAuth(keytab="./user.keytab", deploy_keytab=True)` which already present in the source directory), keytab is copied with new name in format `${principal}_${md5(file)}.keytab`. This also prevents issues like using different keytabs different Kafka by instances which have the same file name.
3. Updated implementation of `_validate_keytab` validator - function for checking keytab availability is already …

[DOP-8019] Improve Kafka.KerberosAuth

---

onetl/connection/db_connection/db_connection.py
onetl/connection/db_connection/greenplum.py
onetl/connection/db_connection/hive.py
onetl/connection/db_connection/jdbc_connection.py
onetl/connection/db_connection/jdbc_mixin.py
onetl/connection/db_connection/kafka/connection.py
onetl/connection/db_connection/mongodb.py
onetl/connection/db_connection/oracle.py
onetl/connection/file_connection/file_connection.py
onetl/connection/file_df_connection/spark_file_df_connection.py
onetl/connection/file_df_connection/spark_s3/connection.py
onetl/core/file_filter/file_filter.py
onetl/core/file_limit/file_limit.py
onetl/db/db_reader/db_reader.py
onetl/db/db_writer/db_writer.py
onetl/file/file_df_reader/file_df_reader.py
onetl/file/file_df_writer/file_df_writer.py
onetl/file/file_downloader/file_downloader.py
onetl/file/file_mover/file_mover.py
onetl/file/file_uploader/file_uploader.py
onetl/hwm/store/base_hwm_store.py
onetl/log.py
onetl/plugins/import_plugins.py
onetl/strategy/base_strategy.py
onetl/strategy/hwm_strategy.py
tests/.coveragerc
tests/tests_integration/tests_db_connection_integration/test_kafka_integration.py
tests/tests_integration/tests_strategy_integration/tests_incremental_batch_strategy_integration/test_strategy_incremental_batch_kafka.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_clickhouse.py

* Added argument `logger` to all logging functions. It is required to pass actual module name to log context.
* Added `stacklevel` argument to all logging functions. It is required to properly detect file name and line of function caller. Each function passes original stacklevel plus 1 to exclude itself from logging.
* Improved `log_collection` - added option `max_items` which allows to hide too many elements from an input, showing only N first ones and a remainder. This previously was implemented in HWMStrategy to show current HWM value, now it is also used in Kafka connector to show bootstrap servers list (it can be huge).
Before:
```
INFO     onetl.hwm.store.base_hwm_store:base_hwm_store.py:113 |onETL| Using YAMLHWMStore as HWM Store
INFO …
```

[DOP-8112] Log real module, file and line number

---

onetl/file/file_df_writer/file_df_writer.py

`target_path` cannot be `None`, this does not make any sense.

[DOP-8132] FileDFWriter.target_path cannot be None

---

docs/changelog/next_release/138.bugfix.rst
onetl/connection/db_connection/kafka/connection.py
tests/tests_integration/tests_core_integration/tests_db_reader_integration/test_kafka_reader_integration.py

Someone could pass non-existing Kafka topic name to DBReader, and this didn't raise any exception. Fixed.

[DOP-8511] Check if Kafka topic exists before read

---

docs/changelog/next_release/131.bugfix.rst
docs/changelog/next_release/131.improvement.rst
onetl/connection/db_connection/kafka/connection.py
onetl/connection/db_connection/kafka/options.py
tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_kafka_writer_integration.py
tests/tests_unit/tests_db_connection_unit/test_kafka_unit.py

* Fixed validation of `headers` column is written to Kafka with default `Kafka.WriteOptions()` - `includeHeaders` had no default value, so instead of raising an exception, column value was just ignored. Now default value is explicitly set to `False`.
* Add check for Spark version to `Kafka.write_df_to_target`, raise exception if user passed `include_headers=True` on Spark 2.4, there this option does not exist.
* Reviewed list of columns user can pass to `DBWriter.run` for Kafka - `timestamp` and `timestampType` are not supported by Spark, `offset` is not supported by Kafka.
* Add more unit tests for Kafka options

[DOP-8208] Fix validation ot includeHeaders

---

docs/changelog/next_release/144.feature.rst
onetl/connection/db_connection/jdbc_connection/connection.py
onetl/connection/db_connection/jdbc_connection/options.py
tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_postgres_writer_integration.py
tests/tests_unit/tests_db_connection_unit/test_jdbc_options_unit.py

- add `ignore` and `error` modes `(if_exists=...)` to `JDBC.WriteOptions`
- add unit and integration tests
- updated documentation

[DOP-8665] - Allow modes "ignore" and "error" in JDBC.WriteOptions

---

docs/changelog/next_release/145.feature.rst
onetl/connection/db_connection/mongodb/connection.py
onetl/connection/db_connection/mongodb/options.py
tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_greenplum_writer_integration.py
tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_mongodb_writer_integration.py
tests/tests_unit/tests_db_connection_unit/test_mongodb_unit.py

- add `ignore` and `error` modes (`if_exists=...)` to `MongoDB.WriteOptions`
- add unit and integration tests
- updated documentation

[DOP-8664] - Allow modes "ignore" and "error" in MongoDB.WriteOptions

---

docs/changelog/next_release/143.feature.rst
docs/connection/db_connection/kafka/read.rst
onetl/connection/db_connection/hive/connection.py
onetl/connection/db_connection/hive/options.py
tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_hive_writer_integration.py
tests/tests_unit/tests_db_connection_unit/test_hive_unit.py

- add `ignore` and `error` modes `(if_exists=...)` to `Hive.WriteOptions`
- add unit and integration tests
- updated documentation

[DOP-8647] - Allow modes "ignore" and "error" in Hive.WriteOptions

---

README.rst
docs/install/files.rst
docs/install/full.rst
docs/install/index.rst
docs/install/kerberos.rst
docs/install/python_packages.rst
docs/install/spark.rst

* Moved `Minimal installation` to the root of instruction `How to install`
* Separated installing different dependencies (file connections, Spark, Kerberos, full bundle) to different pages.
* Merged instruction of installing Spark and injecting Java packages to Spark to one page.
See https://onetl--155.org.readthedocs.build/en/155/install/index.html

[DOP-9007] Rearrange installation documentation

---

docs/changelog/next_release/154.improvement.rst
docs/conf.py
docs/connection/db_connection/greenplum/execute.rst
docs/connection/db_connection/greenplum/prerequisites.rst
docs/connection/db_connection/greenplum/read.rst
docs/connection/db_connection/greenplum/write.rst
onetl/connection/db_connection/greenplum/connection.py
onetl/connection/db_connection/greenplum/options.py
onetl/connection/file_df_connection/spark_s3/connection.py
requirements/docs.txt

Drastically improve `Greenplum` documentation:
* Added [information](https://onetl--154.org.readthedocs.build/en/154/connection/db_connection/greenplum/prerequisites.html) about network ports, grants, `pg_hba.conf` and so on.
* Added interaction schemas for [reading](https://onetl--154.org.readthedocs.build/en/154/connection/db_connection/greenplum/read.html#interaction-schema), [writing](https://onetl--154.org.readthedocs.build/en/154/connection/db_connection/greenplum/write.html#interaction-schema) and [executing](https://onetl--154.org.readthedocs.build/en/154/connection/db_connection/greenplum/execute.html) statements in Greenplum, using [PlantUML](https://plantuml.com).
* Added [recommendations](https://onetl--154.org.readthedocs.build/en/154/connection/db_connection/greenplum/read.ht …

[DOP-9085] Improve Greenplum documentation

---

.github/workflows/data/clickhouse/matrix.yml
.github/workflows/data/core/matrix.yml
.github/workflows/data/hdfs/matrix.yml
.github/workflows/data/hive/matrix.yml
.github/workflows/data/kafka/matrix.yml
.github/workflows/data/mssql/matrix.yml
.github/workflows/data/mysql/matrix.yml
.github/workflows/data/oracle/matrix.yml
.github/workflows/data/postgres/matrix.yml
.github/workflows/data/s3/matrix.yml
.github/workflows/data/teradata/matrix.yml
README.rst
docs/changelog/next_release/159.feature.rst
onetl/connection/db_connection/clickhouse/connection.py
onetl/connection/db_connection/hive/connection.py
onetl/connection/db_connection/kafka/connection.py
onetl/connection/db_connection/mssql/connection.py
onetl/connection/db_connection/mysql/connection.py
onetl/connection/db_connection/oracle/connection.py
onetl/connection/db_connection/postgres/connection.py
onetl/connection/db_connection/teradata/connection.py
onetl/connection/file_df_connection/spark_hdfs/connection.py
onetl/connection/file_df_connection/spark_local_fs.py
onetl/connection/file_df_connection/spark_s3/connection.py
onetl/file/format/avro.py
requirements/tests/spark-3.5.0.txt
tests/tests_unit/test_file/test_format_unit/test_avro_unit.py
tests/tests_unit/tests_db_connection_unit/test_greenplum_unit.py
tests/tests_unit/tests_file_df_connection_unit/test_spark_s3_unit.py

Nightly tests with latest pyspark version shown that some classes do not yet support Spark 3.5.0:
https://github.com/MobileTeleSystems/onetl/actions/runs/6336863272/job/17210825113
* MongoDB fails with sone internal error. This could be caused by used package version (10.1 then latest is 10.2).
* Excel [does not have package](https://github.com/crealytics/spark-excel/issues/787) for 3.5.0 yet: https://mvnrepository.com/artifact/com.crealytics/spark-excel
Other connection and file formats do support 3.5.0, so updated documentation of connectors & Readme.

[DOP-9653] Test onETL compatibility with Spark 3.5.0

---

docs/changelog/next_release/164.bugfix.rst
docs/changelog/next_release/164.improvement.rst
onetl/connection/db_connection/db_connection/connection.py
onetl/connection/db_connection/hive/connection.py
onetl/connection/db_connection/mongodb/connection.py
onetl/connection/file_df_connection/spark_file_df_connection.py
tests/fixtures/spark_mock.py
tests/tests_unit/tests_db_connection_unit/test_clickhouse_unit.py
tests/tests_unit/tests_db_connection_unit/test_greenplum_unit.py
tests/tests_unit/tests_db_connection_unit/test_hive_unit.py
tests/tests_unit/tests_db_connection_unit/test_kafka_unit.py
tests/tests_unit/tests_db_connection_unit/test_mongodb_unit.py
tests/tests_unit/tests_db_connection_unit/test_mssql_unit.py
tests/tests_unit/tests_db_connection_unit/test_mysql_unit.py
tests/tests_unit/tests_db_connection_unit/test_oracle_unit.py
tests/tests_unit/tests_db_connection_unit/test_postgres_unit.py
tests/tests_unit/tests_db_connection_unit/test_teradata_unit.py
tests/tests_unit/tests_file_df_connection_unit/test_spark_hdfs_unit.py
tests/tests_unit/tests_file_df_connection_unit/test_spark_local_fs_unit.py
tests/tests_unit/tests_file_df_connection_unit/test_spark_s3_unit.py

1. `Hive.check()` now does not return successful result when Hive Metastore is not available.
2. Added check to all DB and FileDF connections that Spark session is alive.

[DOP-6758] Fix Hive.check() behavior when Hive Metastore is not available

---

.github/workflows/data/local-fs/matrix.yml
.github/workflows/data/local-fs/tracked.txt
docs/changelog/next_release/161.feature.rst
onetl/file/format/excel.py
tests/fixtures/spark.py
tests/tests_integration/test_file_format_integration/test_excel_integration.py
tests/tests_unit/test_file/test_format_unit/test_excel_unit.py

Excel package now has support of Spark 3.5.0, upgraded to latest version.
For now it is blocked by https://github.com/crealytics/spark-excel/issues/789.

[DOP-9653] Update Excel package version to 0.20.1

---

docs/changelog/next_release/183.bugfix.rst
onetl/hooks/hook.py
onetl/hooks/slot.py

It looks like Pylance (VS Code extension for Python) does not recognize [typing_extensions.ParamSpec](https://docs.python.org/3/library/typing.html#typing.ParamSpec). 
With ParamsSpec:
Without:
`ParamSpec` is a recommended way to tell linters how inputs of `callable: Callable[Spec, ReturnType]` are passed to `def new_callable(*Spec.args, **Spec.kwargs) -> ReturnType:`. 
Fortunately, there is another (but less precise) way to describe this - `Callable[..., ReturnType]`. This is used for now.

[DOP-11371] Fix @slot decorator

---

tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_clickhouse.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_greenplum.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_hive.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_mongodb.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_mssql.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_mysql.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_oracle.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_postgres.py

Added test that user can pass exact HWM type instead of `AutoDetectHWM`, and HWM type autodetection will not be used in this case. This can produce weird results, and behavior depends on database type, but it's up to user.

[DOP-9787] Add test for explicit DBReader.hwm type

---

docs/changelog/next_release/189.breaking.rst
onetl/file/file_downloader/file_downloader.py
onetl/strategy/incremental_strategy.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_file.py

Using `FileDownloader` with `DownloadOptions(workers=N)` has a potential race condition because there is no thread lock on `Strategy.hwm` attribute.
Instead of adding such a lock, I've updated current implementation to update HWM only after all files were handled. This also avoid issuing too many requests to HWM Store which could potentially DDoS the service if large number of files are being downloaded.

[DOP-9787] Avoid race condition in FileDownloader while updating HWM

---

docs/changelog/next_release/190.feature.rst
onetl/db/db_reader/db_reader.py
onetl/db/db_writer/db_writer.py
onetl/file/file_df_reader/file_df_reader.py
onetl/file/file_df_writer/file_df_writer.py
onetl/file/file_downloader/file_downloader.py
onetl/file/file_mover/file_mover.py
onetl/file/file_uploader/file_uploader.py
onetl/strategy/incremental_strategy.py

`connection.check()` is being called only once inside `.run()` method of DBReader/FileDownloader/... object, to avoid printing same connection detauls into logs again and again.
Before:
```log
|onETL| Using IncrementalBatchStrategy as a strategy
step = 10
|IncrementalBatchStrategy| First iteration
=================================== DBReader.run() starts ===================================
|DBReader| Getting Spark type for HWM expression: 'hwm_int'
|Postgres| Fetching schema of table 'onetl.test_b47b282cf4' ...
|Postgres| Schema fetched.
|DBReader| Got Spark field: StructField('hwm_int', LongType(), True)
|DBReader| Detected HWM type: 'ColumnIntHWM'
|IncrementalBatchStrategy| Fetching HWM from MemoryHWMStore:
name = 'd5930cc53b'
|IncrementalBatchStrategy| Fetched HWM:
hwm = ColumnIntHWM( …
```

[DOP-11682] Cache result of connection.check()

---

CONTRIBUTING.rst
onetl/base/base_db_connection.py
onetl/connection/db_connection/db_connection/dialect.py
onetl/connection/db_connection/kafka/connection.py
onetl/connection/db_connection/kafka/dialect.py
onetl/db/db_reader/db_reader.py
onetl/hwm/auto_hwm.py
onetl/impl/frozen_model.py
requirements/core.txt
tests/tests_unit/test_db/test_db_reader_unit/test_common_reader_unit.py
tests/tests_unit/test_db/test_db_reader_unit/test_kafka_reader_unit.py
tests/tests_unit/tests_db_connection_unit/test_kafka_unit.py

- add `KeyValueIntHWM` support in `DBReader` (update `etl-entities` version to `2.2.0`)
- add following tests and documentation
- add **Release Process** in Contribution guide

[DOP-11980] - add KeyValueIntHWM support in DBReader

---

onetl/connection/db_connection/clickhouse/connection.py
onetl/connection/db_connection/clickhouse/dialect.py
onetl/connection/db_connection/jdbc_mixin/connection.py

Clickhouse's `min`/`max` functions return `0` if there is no data in the source. There was a workaround for that to return `None` from `get_min_max_values`.
But there are also `minOrNull`/`maxOrNull` variants of these functions which return `null` for empty result. Switched to these functions to simplify code a bit.

[DOP-11906] Remove min/max workaround for Clickhouse

---

docs/changelog/next_release/211.improvement.rst
docs/connection/db_connection/clickhouse/execute.rst
docs/connection/db_connection/clickhouse/index.rst
docs/connection/db_connection/clickhouse/prerequisites.rst
docs/connection/db_connection/clickhouse/read.rst
docs/connection/db_connection/clickhouse/sql.rst
docs/connection/db_connection/clickhouse/types.rst
docs/connection/db_connection/clickhouse/write.rst
onetl/connection/db_connection/clickhouse/connection.py
onetl/connection/db_connection/jdbc_mixin/connection.py

* Improved Clickhouse's documentation about reading, writing and executing statements. Previously it was just crosslinks to DBReader, DBWriter and connection own methods docstrings. Now there are more Clickhouse-specific examples and recommendations
* Added new section describing type compatibility between Clickhouse and Spark, including some recommendations for reading/writing unsupported column types.
* Added new section describing which actions should be performed to connect to Clickhouse.
See https://onetl--211.org.readthedocs.build/en/211/connection/db_connection/clickhouse/index.html
If new documentation layout will be approved, we can drop generic examples from ``JDBC.fetch()``, ``JDBC.execute()``, ``JDBC.sql()``, ``JDBC.JDBCOptions`` and so on, and replace them with DB-specific …

[DOP-11906] Improve Clickhouse documentation

---

docs/changelog/next_release/228.improvement.rst
docs/connection/db_connection/clickhouse/execute.rst
docs/connection/db_connection/greenplum/execute.rst
docs/connection/db_connection/greenplum/index.rst
docs/connection/db_connection/greenplum/prerequisites.rst
docs/connection/db_connection/greenplum/read.rst
docs/connection/db_connection/greenplum/types.rst
docs/connection/db_connection/greenplum/write.rst
onetl/connection/db_connection/greenplum/connection.py

* Added [separated page](https://onetl--228.org.readthedocs.build/en/228/connection/db_connection/greenplum/types.html) with Greenplum <-> Spark types mapping, and recommendations related to type casts.
* Describe set of [DBReader features](https://onetl--228.org.readthedocs.build/en/228/connection/db_connection/greenplum/read.html) supported by Greenplum connector.
* Added more examples to reading & writing data to Greenplum, and using `fetch` and `execute` methods.

[DOP-13251] Add Greenplum type mapping to documentation

---

docs/changelog/next_release/228.improvement.rst
docs/connection/db_connection/greenplum/prerequisites.rst

Sometimes Greenplum connector cannot resolve Spark worker host IP address, which leads to failing read/write to Greenplum. Add related notes to "Prerequisites" section of documentation.
See https://onetl--231.org.readthedocs.build/en/231/connection/db_connection/greenplum/prerequisites.html#set-connection-host

[DOP-13558] Document using Greenplum connector with IP resolution issues

---

docs/changelog/next_release/237.feature.rst
onetl/connection/db_connection/mongodb/connection.py
tests/tests_integration/tests_db_connection_integration/test_mongodb_integration.py

Sometimes it is handy to just fetch some data from MongoDB to see infered schema. But `MongoDB.pipeline` requires to pass `pipeline={...}` argument, so users have to pass here some nonsense to bypass this.
Now this argument is optional.

[DOP-13681] Allow empty pipeline in MongoDB.pipeline

---

docs/changelog/next_release/238.bugfix.rst
onetl/base/base_db_connection.py
onetl/connection/db_connection/dialect_mixins/support_columns_list.py
onetl/db/db_reader/db_reader.py
tests/tests_unit/test_db/test_db_reader_unit/test_common_reader_unit.py

Allow passing string to `DBReader(columns=...)` as it was allowed in v0.9.x and below. But this is a deprecated syntax, so user will see a warning.

[DOP-13739] Return back handling DBReader(columns="string")

---

docs/changelog/next_release/249.feature.rst
docs/changelog/next_release/251.feature.rst
onetl/connection/db_connection/clickhouse/connection.py
onetl/connection/db_connection/postgres/connection.py
tests/tests_unit/tests_db_connection_unit/test_clickhouse_unit.py
tests/tests_unit/tests_db_connection_unit/test_postgres_unit.py

- `Postgres` connection now uses PostgreSQL JDBC driver ``42.7.3``, upgraded from ``42.6.0``, and supports passing custom versions: ``Postgres.get_packages(package_version=...)``.
- Update following tests and documentation

[DOP-13849] - upgrade Postgres packages

---

docs/changelog/next_release/253.feature.rst
onetl/connection/db_connection/mysql/connection.py
tests/tests_unit/tests_db_connection_unit/test_mysql_unit.py

- `MySQL` connection now uses MySQL JDBC driver ``8.3.0``, upgraded from ``8.0.33``, and supports passing custom versions: ``MySQL.get_packages(package_version=...)``.
- Update following documentation and tests.

[DOP-13851] - upgrade MySql packages

---

docs/changelog/next_release/254.feature.rst
onetl/connection/db_connection/mssql/connection.py
tests/tests_unit/tests_db_connection_unit/test_mssql_unit.py

- `MSSQL` connection now uses Microsoft SQL Server JDBC driver ``12.7.0``, upgraded from ``12.2.0``, and supports passing custom versions: ``MSSQL.get_packages(java_version=..., package_version=...)``.
- Update following documentation and tests.

[DOP-13852] - upgrade MSSQL packages

---

docs/changelog/next_release/255.feature.rst
onetl/connection/db_connection/mongodb/connection.py
tests/tests_unit/tests_db_connection_unit/test_mongodb_unit.py

- `MongoDB` connection now uses MongoDB Spark connector ``10.2.2``, upgraded from ``10.1.1``, and supports passing custom versions: ``MongoDB.get_packages(scala_version=..., connector_version=...)``.
- Update following documentation and tests.

[DOP-13853] - upgrade MongoDB packages

---

docs/changelog/next_release/256.feature.rst
onetl/connection/db_connection/teradata/connection.py
tests/tests_unit/tests_db_connection_unit/test_teradata_unit.py

- `Teradata` connection now uses Teradata JDBC driver ``20.00.00.19``, upgraded from ``17.20.00.15``, and supports passing custom versions: ``Teradata.get_packages(package_version=...)``.
- Update following documentation and tests.

[DOP-14492] - Teradata supports passing custom versions

---

docs/changelog/next_release/257.feature.rst
docs/connection/db_connection/clickhouse/types.rst
docs/connection/db_connection/greenplum/types.rst
docs/connection/db_connection/mysql/types.rst
docs/connection/db_connection/oracle/types.rst
docs/connection/db_connection/postgres/types.rst
docs/file_df/file_formats/json.rst
onetl/file/format/json.py
tests/tests_integration/test_file_format_integration/test_json_integration.py

- Add ``JSON.parse_column`` and ``JSON.serialize_column`` methods to facilitate direct parsing of JSON strings into Spark DataFrame columns and serialization of structured DataFrame columns back into JSON strings.
- Update following tests and documentation

[DOP-13840] - add JSON.parse_column and JSON.serialize_column methods

---

docs/changelog/next_release/255.feature.rst
docs/connection/db_connection/mongodb/types.rst
onetl/connection/db_connection/mongodb/connection.py
tests/tests_unit/tests_db_connection_unit/test_mongodb_unit.py

Update MongoDB package to latest version:
https://mvnrepository.com/artifact/org.mongodb.spark/mongo-spark-connector

[DOP-13853] Update MongoDB package to 10.2.3

---

docs/changelog/next_release/265.feature.rst
docs/connection/db_connection/kafka/format_handling.rst
docs/file_df/file_formats/avro.rst
onetl/file/format/avro.py
requirements/tests/base.txt
tests/tests_integration/test_file_format_integration/test_avro_integration.py

- Add ``Avro.parse_column`` and ``Avro.serialize_column`` methods to enhance the handling of Avro binary data within Spark. 
- Add following tests and documentation. 

[DOP-13845] -  implement Avro.parse_column, Avro.serialize_column

---

docs/changelog/next_release/275.improvement.rst
docs/connection/file_df_connection/spark_s3/troubleshooting.rst
docs/index.rst
docs/logging.rst
docs/troubleshooting/index.rst
docs/troubleshooting/spark.rst

* Improve documentation about logging, add logs example
* Add separated page for Spark troubleshooting - how to restart Spark session, how to change driver & executor logs level.
* Add generic troubleshooting guide.

[DOP-14059] Add Troubleshooting guide

---

docs/changelog/next_release/274.feature.rst
docs/conf.py
docs/connection/db_connection/clickhouse/execute.rst
docs/connection/db_connection/greenplum/execute.rst
docs/connection/db_connection/mssql/execute.rst
docs/connection/db_connection/mysql/execute.rst
docs/connection/db_connection/oracle/execute.rst
docs/connection/db_connection/postgres/execute.rst
docs/connection/db_connection/teradata/execute.rst
onetl/connection/db_connection/greenplum/connection.py
onetl/connection/db_connection/jdbc_mixin/connection.py
onetl/connection/db_connection/jdbc_mixin/options.py
onetl/connection/db_connection/oracle/connection.py
onetl/connection/db_connection/postgres/connection.py
tests/tests_integration/tests_db_connection_integration/test_greenplum_integration.py
tests/tests_integration/tests_db_connection_integration/test_postgres_integration.py
tests/tests_unit/tests_db_connection_unit/test_db_options_unit.py
tests/tests_unit/tests_db_connection_unit/test_greenplum_unit.py
tests/tests_unit/tests_db_connection_unit/test_jdbc_options_unit.py

- Divide general ``JDBCOptions`` into ``FetchOptions`` for fetching data and ``ExecuteOptions`` for executing statements.
- Add following tests and documentation.

[DOP-15749] - add ExecuteOptions, FetchOptions

---

docs/changelog/next_release/278.improvement.rst
docs/connection/db_connection/clickhouse/execute.rst
docs/connection/db_connection/greenplum/execute.rst
docs/connection/db_connection/greenplum/read.rst
docs/connection/db_connection/hive/execute.rst
docs/connection/db_connection/hive/index.rst
docs/connection/db_connection/hive/prerequisites.rst
docs/connection/db_connection/hive/read.rst
docs/connection/db_connection/hive/sql.rst
docs/connection/db_connection/hive/write.rst
docs/connection/db_connection/mysql/execute.rst
docs/connection/db_connection/postgres/execute.rst
docs/connection/db_connection/teradata/execute.rst
onetl/connection/db_connection/hive/connection.py
onetl/connection/db_connection/hive/options.py

* Add [Prerequisites](https://onetl--278.org.readthedocs.build/en/278/connection/db_connection/hive/index.html) section to Hive documentation, describing some config options required to access Hive metastore.
* Split up instructions about reading data using [DBReader](https://onetl--278.org.readthedocs.build/en/278/connection/db_connection/hive/read.html) and [Hive.sql](https://onetl--278.org.readthedocs.build/en/278/connection/db_connection/hive/sql.html), improve examples.
* Add recommendations about reading & [writing data](https://onetl--278.org.readthedocs.build/en/278/connection/db_connection/hive/write.html) to Hive, e.g. using partitioning, compression, column-based file formats and so on.
* Add more examples to [Executing …

[DOP-14042] Improve Hive documentation

---

.github/workflows/data/mongodb/matrix.yml
docs/changelog/next_release/255.feature.rst
docs/connection/db_connection/mongodb/prerequisites.rst
docs/connection/db_connection/mongodb/types.rst
onetl/connection/db_connection/mongodb/connection.py
tests/tests_unit/tests_db_connection_unit/test_mongodb_unit.py

MongoDB connection recently updated from 10.2.3 to 10.3.0, adding support of Spark 3.5.x.

[DOP-13853] Update MongoDB package to 10.3.0

---

README.rst
docs/changelog/next_release/287.feature.rst
docs/connection/db_connection/mssql/prerequisites.rst
docs/logging.rst
onetl/connection/db_connection/clickhouse/connection.py
onetl/connection/db_connection/jdbc_connection/connection.py
onetl/connection/db_connection/mssql/connection.py
onetl/connection/db_connection/mysql/connection.py
onetl/connection/db_connection/oracle/connection.py
onetl/connection/db_connection/postgres/connection.py
onetl/connection/db_connection/teradata/connection.py
tests/tests_unit/tests_db_connection_unit/test_clickhouse_unit.py
tests/tests_unit/tests_db_connection_unit/test_greenplum_unit.py
tests/tests_unit/tests_db_connection_unit/test_mssql_unit.py
tests/tests_unit/tests_db_connection_unit/test_mysql_unit.py
tests/tests_unit/tests_db_connection_unit/test_oracle_unit.py
tests/tests_unit/tests_db_connection_unit/test_postgres_unit.py
tests/tests_unit/tests_db_connection_unit/test_teradata_unit.py

Make MSSQL.port optional, to allow using [instanceName](https://learn.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver16#named-and-multiple-sql-server-instances).

[DOP-16270] Allow passing instanceName to MSSQL(extra=...)

---

.github/workflows/data/db/tracked.txt
docs/changelog/next_release/288.bugfix.rst
onetl/connection/db_connection/greenplum/connection.py
onetl/connection/db_connection/jdbc_connection/connection.py
onetl/connection/db_connection/jdbc_connection/options.py
onetl/connection/db_connection/jdbc_mixin/connection.py
onetl/connection/db_connection/postgres/connection.py

Currently `JDBC.WriteOptions` have `fetchsize` option. This should not be the case.
Instead of inheriting `JDBC.ReadOptions`, `JDBC.SQLOptions` and `JDBC.WriteOptions from legacy `JDBC.JDBCOptions`, inherit them from `GenericOptions`. Copy `query_timeout` to both of these classes, as Spark can accept this option in both read and write operations.

[DOP-15764] Remove fetchsize from JDBCWriteOptions

---

docs/changelog/next_release/292.feature.rst
docs/connection/db_connection/hive/write.rst
onetl/connection/db_connection/hive/connection.py
onetl/connection/db_connection/hive/options.py
tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_hive_writer_integration.py

- Add support for specifying file formats (``ORC``, ``Parquet``, ``CSV``, etc.) in ``HiveWriteOptions.format``: 
```
options = Hive.WriteOptions(
if_exists="append",
partition_by="reg_id",
format=ORC(compression="snappy"),
)
```
- Update following tests and documentation

[DOP-16103] - add class format to HiveWriteOptions

---

docs/changelog/next_release/303.feature.1.rst
docs/changelog/next_release/303.feature.2.rst
onetl/_util/spark.py
onetl/base/base_db_connection.py
onetl/base/base_file_df_connection.py
onetl/connection/db_connection/hive/connection.py
onetl/connection/db_connection/jdbc_connection/connection.py
onetl/connection/db_connection/jdbc_mixin/connection.py
onetl/connection/db_connection/oracle/connection.py
onetl/db/db_writer/db_writer.py
onetl/file/file_df_writer/file_df_writer.py
tests/.coveragerc
tests/tests_integration/tests_db_connection_integration/test_postgres_integration.py

Use `SparkMetricsRecorded` to collect Spark metrics from those methods:
* `DBWriter.run()`
* `FileDFWriter.run()`
* `JDBC.fetch()`, `JDBC.execute()`
* `Hive.execute()`
And log these metrics. But the only metrics logged in INFO level are JDBC ones, as they are reliable, others are DEBUG only.
Also I've added function to get estimated size of in-memory dataframe using Spark's `SizeEstimator`. This is an approximate metric, but it always present.
Few examples:
`DBWriter.run` with Hive:
```
DEBUG |DBWriter| Recorded metrics (may be incomplete!):
DEBUG         Output:
DEBUG             Written rows: 100
DEBUG             Written size: 2.5 kB
DEBUG             Created files: 1
DEBUG         Executor:
DEBUG             Total run time: 0.13 seconds
DEBUG             Total CPU time: 0.04 seconds …
```

[DOP-18571] Collect and log Spark metrics in various method calls

---

docs/changelog/next_release/308.bugfix.rst
onetl/connection/db_connection/greenplum/connection.py
tests/tests_unit/tests_db_connection_unit/test_greenplum_unit.py

Add options passed to `Greenplum(extra={"some": "value"})` to JDBC URL query part.
Add unit tests.

[DOP-19024] Fix passing custom JDBC options to Greenplum.extra

---

docs/changelog/next_release/316.bugfix.1.rst
docs/changelog/next_release/316.bugfix.2.rst
onetl/log.py

Currently KeyValueIntHWM in printed to logs like this:
```|IncrementalStrategy| Fetched HWM:
hwm = KeyValueIntHWM(
name = 'test_offset1',
entity = 'test_topic',
expression = 'offset',
value = [
0,
]
)
```
But it should be:
```|IncrementalStrategy| Fetched HWM:
hwm = KeyValueIntHWM(
name = 'test_offset1',
entity = 'test_topic',
expression = 'offset',
value = {
0: 123,
}
)
```
I've added handling of dict and set to `log_collection` function.
Also fixed bug then logging with INFO level lead hiding up Kafka addresses:
```
|Kafka| Checking connection availability...
|Kafka| Using connection parameters:
cluster = 'cluster'
addresses = [
]
protocol = KafkaPlaintextProtocol()
auth = None
extra = {}
```
Now it is:
```
|Kafka| Checking connection availability...
|Kafka| Using connection parameters: …
```

[DOP-21408] Fix logging KeyValueIntHWM using log_hwm

---

.github/workflows/test-mssql.yml
docs/changelog/0.12.3.rst
docs/changelog/index.rst
onetl/connection/db_connection/dialect_mixins/support_name_with_schema_only.py
tests/tests_unit/test_db/test_db_reader_unit/test_clickhouse_reader_unit.py
tests/tests_unit/test_db/test_db_reader_unit/test_greenplum_reader_unit.py
tests/tests_unit/test_db/test_db_reader_unit/test_hive_reader_unit.py
tests/tests_unit/test_db/test_db_reader_unit/test_mssql_reader_unit.py
tests/tests_unit/test_db/test_db_reader_unit/test_mysql_reader_unit.py
tests/tests_unit/test_db/test_db_reader_unit/test_oracle_reader_unit.py
tests/tests_unit/test_db/test_db_reader_unit/test_postgres_reader_unit.py
tests/tests_unit/test_db/test_db_reader_unit/test_teradata_reader_unit.py
tests/tests_unit/test_db/test_db_writer_unit/test_clickhouse_writer_unit.py
tests/tests_unit/test_db/test_db_writer_unit/test_greenplum_writer_unit.py
tests/tests_unit/test_db/test_db_writer_unit/test_hive_writer_unit.py
tests/tests_unit/test_db/test_db_writer_unit/test_mssql_writer_unit.py
tests/tests_unit/test_db/test_db_writer_unit/test_mysql_writer_unit.py
tests/tests_unit/test_db/test_db_writer_unit/test_oracle_writer_unit.py
tests/tests_unit/test_db/test_db_writer_unit/test_postgres_writer_unit.py
tests/tests_unit/test_db/test_db_writer_unit/test_teradata_writer_unit.py

`DBReader(name=...)` and `DBWriter(name=...)` validators are too strict, and don't allow passing table names with multiple dots. Fixed.

[DOP-21634] Make DBReader and DBWriter table name requirements less strict

---

docs/changelog/next_release/319.bugfix.rst
onetl/connection/db_connection/clickhouse/dialect.py
onetl/connection/db_connection/mssql/dialect.py
onetl/connection/db_connection/oracle/dialect.py

`ORA_HASH(col, N)` returns results from 0 to N including N (N+1 in total). Spark creates exactly N partitions, so last partition gets twice the data relative to other ones.
Fixed by calling `ORA_HASH(col, N-1)`. Other JDBC sources don't have such an issue, as they use modulo which always returns values from 0 to N-1.

[DOP-21732] Fix Oracle reading with partitioning_mode=hash

---

docs/changelog/0.12.5.rst
docs/changelog/index.rst
onetl/connection/db_connection/clickhouse/dialect.py
onetl/connection/db_connection/jdbc_connection/options.py
onetl/connection/db_connection/mssql/dialect.py
onetl/connection/db_connection/mysql/dialect.py
onetl/connection/db_connection/oracle/dialect.py
onetl/connection/db_connection/postgres/dialect.py
onetl/connection/db_connection/teradata/dialect.py
tests/fixtures/processing/base_processing.py
tests/fixtures/processing/clickhouse.py
tests/fixtures/processing/mongodb.py
tests/tests_integration/tests_core_integration/tests_db_reader_integration/test_clickhouse_reader_integration.py
tests/tests_integration/tests_core_integration/tests_db_reader_integration/test_mssql_reader_integration.py
tests/tests_integration/tests_core_integration/tests_db_reader_integration/test_mysql_reader_integration.py
tests/tests_integration/tests_core_integration/tests_db_reader_integration/test_oracle_reader_integration.py
tests/tests_integration/tests_core_integration/tests_db_reader_integration/test_postgres_reader_integration.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_oracle.py

* Fix issue when using `{"partitioning_mode": "hash", "partitionColumn": "integer_col"}` in MSSQL raised an error:
```
com.microsoft.sqlserver.jdbc.SQLServerException: Argument data type int is invalid for argument 2 of hashbytes function.
```
Now it supports any column type.
* Add tests for all combinations of `partitioning_mode` with `partitionColumn` types for all JDBC connectors (except Teradata).
* Use the fastest available hash function for `partitioning_mode=hash` - somewhere it is `MD5`, somewhere it is some kind of internal hash function which is used for hash indexes.
* Fix `partitioning_mode=mod` could return negative results for negative column values, and thus resulting a data skew (because all `mod(col, N) <= lowerBound` values are passed into first partition).
(see …

[DOP-21813] Fix partitioning_mode=hash and cover with tests

---

docs/changelog/next_release/325.feature.rst
docs/file/file_filters/file_size_filter.rst
docs/file/file_filters/index.rst
onetl/file/filter/__init__.py
onetl/file/filter/file_size.py
setup.cfg
tests/tests_unit/test_file/test_filter/test_file_size_range.py

Introduce new class `FileSizeRange(min=..., max=...)`.
We haven't reached consensus regarding class name, other possible options are `MinFileSize(...)` and `MaxFileSize(...)`.

[DOP-22143] Introduce FileSizeRange

---

docs/changelog/next_release/326.feature.rst
docs/file/file_limits/index.rst
docs/file/file_limits/total_files_size.rst
onetl/file/file_downloader/file_downloader.py
onetl/file/file_mover/file_mover.py
onetl/file/limit/__init__.py
onetl/file/limit/max_files_count.py
onetl/file/limit/total_files_size.py
setup.cfg
tests/tests_unit/test_file/test_limit/test_total_files_size.py

Introduce `TotalFilesSize(...)` limit class.

[DOP-22144] Introduce TotalFilesSize limit

---

docs/changelog/next_release/327.breaking.rst
onetl/base/base_file_connection.py
onetl/connection/file_connection/file_connection.py
onetl/core/file_limit/file_limit.py
onetl/file/limit/limits_reached.py
onetl/file/limit/limits_stop_at.py
onetl/file/limit/max_files_count.py
onetl/file/limit/reset_limits.py
onetl/file/limit/total_files_size.py
tests/tests_integration/tests_core_integration/test_file_downloader_integration.py
tests/tests_unit/test_file/test_file_limit_unit.py
tests/tests_unit/test_file/test_limit/test_limits_are_reached.py
tests/tests_unit/test_file/test_limit/test_limits_stop_at.py
tests/tests_unit/test_file/test_limit/test_max_files_count.py
tests/tests_unit/test_file/test_limit/test_reset_limits.py
tests/tests_unit/test_file/test_limit/test_total_files_size.py

After thinking on https://github.com/MobileTeleSystems/onetl/pull/326#pullrequestreview-2546569010, I've desided that `FileConnection.walk` and `FileConnection.listdir` implementation should be changed.
Previously: iterate over all files in the directory, include file to resulting list, stop if limit is reached.
Now: iterate over all files in the directory, check if limit is reached, include file only if it is not.
This is because if user have files list:
* file1.txt (10KB)
* file2.txt (20KB)
* file3.txt (30KB)
and set limit `TotalFileSize("15KB")`, FileDownloader/FileMover should download only file1.txt and skip both file2.txt and file3.txt (because 10KB+20KB already exceeds the limit of 15KB). Previous implementation lead to downloading file2.txt (as limit internal stage recorded 10KB …

[DOP-22144] Change logic of applying limits

---

docs/changelog/next_release/330.feature.rst
docs/file/file_filters/file_mtime_filter.rst
docs/file/file_filters/index.rst
onetl/base/base_file_filter.py
onetl/connection/file_connection/file_connection.py
onetl/connection/file_connection/webdav.py
onetl/file/file_downloader/file_downloader.py
onetl/file/file_mover/file_mover.py
onetl/file/filter/__init__.py
onetl/file/filter/file_mtime.py
onetl/file/filter/file_size.py
onetl/impl/path_repr.py
setup.cfg
tests/tests_integration/tests_core_integration/test_file_downloader_integration.py
tests/tests_integration/tests_core_integration/test_file_mover_integration.py
tests/tests_unit/test_file/test_filter/test_file_modified_time.py
tests/tests_unit/test_file/test_filter/test_file_size_range.py
tests/tests_unit/test_impl_unit.py

Implemented `FileModifiedTime(since=..., until=...)` file filter.
Also improved integration tests for `FileDownloader(filters=[...])` and `FileUploader(filters=[...])` - list of exact filenames is compared when possible, added integration tests for Regexp and FileSizeRange.
I've discovered that `.walk(dir)` or `.listdir(dir)` methods in most of connectors (excluding FTP/FTPS) return timestamp which is rounded to the whole second, but `.get_stat(file)` method may return timestamp with milliseconds or microseconds precision. Added a note to filter documentation.

[DOP-22127] Implement FileModifiedTime filter

---

docs/changelog/next_release/331.dependency.rst
onetl/connection/file_connection/s3.py
onetl/file/file_downloader/file_downloader.py
onetl/strategy/incremental_strategy.py
requirements/core.txt
tests/fixtures/hwm_delta.py
tests/tests_integration/tests_core_integration/test_file_downloader_integration.py
tests/tests_integration/tests_strategy_integration/tests_incremental_strategy_integration/test_strategy_increment_file.py
tests/tests_unit/test_file/test_file_downloader_unit.py

Updated minimal `etl-entities` version to 2.5.0. Added tests and docstrings using new class `FileModifiedTimeHWM`.
Note that currently used FTP client calls method `LIST` which [returns `st_mtime` trucated to whole minutes](https://blog.rebex.net/file-modification-date-and-time-in-ftp) (not even seconds), so FTP/FTPS tests with FileModifiedTimeHWM are skipped for now.

[DOP-22130] Add support for FileModifiedTimeHWM

---

docs/changelog/next_release/334.feature.rst
onetl/connection/db_connection/greenplum/connection.py
onetl/connection/db_connection/jdbc_connection/connection.py
onetl/connection/db_connection/jdbc_mixin/connection.py

Do not keep open JDBC connection as thread-local object attribute. Instead, open connection, execute statement, load result into Spark (if any) and then close connection immediately. This keeps the number of opened DB connections as low as possible, which is crucial for PG/GP.
This may increase the time of each statement being executed, but as I see, tests took just the same time as in `develop` branch.

[DOP-22427] Do not keep open JDBC connection on Spark driver

---

docs/changelog/next_release/337.bugfix.rst
onetl/connection/db_connection/jdbc_mixin/connection.py
onetl/connection/db_connection/mssql/connection.py
onetl/connection/db_connection/mysql/connection.py
tests/tests_integration/tests_db_connection_integration/test_clickhouse_integration.py
tests/tests_integration/tests_db_connection_integration/test_greenplum_integration.py
tests/tests_integration/tests_db_connection_integration/test_mssql_integration.py
tests/tests_integration/tests_db_connection_integration/test_mysql_integration.py
tests/tests_integration/tests_db_connection_integration/test_oracle_integration.py
tests/tests_integration/tests_db_connection_integration/test_postgres_integration.py

Some JDBC drivers respect `java_jdbc_connection.setReadOnly(...)` (Oracle, Clickhouse, Postgres, Greenplum), some don't (MySQL, MSSQL). Fixing this by adding few workarounds for these RDBMS.

[DOP-23742] Fix using conn.setReadOnly(...) for MySQL, MSSQL

---

.env.docker
.env.local
.github/workflows/test-greenplum.yml
.github/workflows/test-postgres.yml
CONTRIBUTING.rst
docker-compose.yml
docs/changelog/next_release/336.bugfix.rst
onetl/connection/db_connection/greenplum/connection.py
onetl/connection/db_connection/postgres/connection.py
tests/tests_integration/tests_db_connection_integration/test_greenplum_integration.py
tests/tests_integration/tests_db_connection_integration/test_postgres_integration.py

Depends on #337.
Fixed issue with writing data to PG/GP instances behind pgbouncer with `pool_mode=transaction`, caused by https://github.com/pgjdbc/pgjdbc/issues/848. Added PGBouncer to docker-compose and CI workflows, running tests on PG/GP with and without PGBouncer.
Behavior is almost the same as before, except rare case of Postgres/Greenplum calling `connection.fetch("SELECT function()")` where `function` calls DML/DDL - previously this failed due to read-only connection, now it's not. This was sacrificed for pgbounce support.

[DOP-23742] Fix writing to Postgres and Greenplum behind PGBouncer

---

.pre-commit-config.yaml
docs/changelog/next_release/338.bugfix.rst
onetl/log.py
tests/tests_integration/tests_core_integration/test_file_downloader_integration.py
tests/tests_integration/tests_core_integration/test_file_mover_integration.py

- Removed sorting of the `filters` collection in logging to avoid issues due to missing comparison methods
- Added an integration test cases to validate behavior when multiple filters are passed to `FileDownloader(filters=[...])` and `FileMover(filters[...])`.

[DOP-23797] Fix FileDownloader with several filters

---

README.rst
docs/changelog/next_release/341.feature.rst
docs/connection/db_connection/kafka/connection.rst
docs/connection/file_df_connection/spark_s3/connection.rst
onetl/connection/db_connection/kafka/connection.py
onetl/connection/file_df_connection/spark_s3/connection.py
tests/fixtures/spark.py
tests/tests_unit/test_db/test_db_reader_unit/test_greenplum_reader_unit.py

`SparkS3.get_packages()` and `Kafka.get_packages()` return list of packages with compile dependency on hadoop client packages which are already a part of Spark/PySpark bundle. Also, `SparkS3` uses `spark-cloud` package depending on lots of cloud clients, like GCP, Azure and so on, which are not required here.
Added `.get_exclude_packages()` method to both of these classes. Using `spark.jar.excludes` mechanism to tell Ivy2 that some transitive packages should be excluded.

[DOP-23968] Add .get_exlude_packages() to SparkS3 and Kafka

---

docs/changelog/next_release/343.breaking.rst
onetl/file/file_df_writer/options.py
onetl/file/file_downloader/options.py
onetl/file/file_mover/options.py
onetl/file/file_uploader/options.py
tests/tests_integration/tests_core_integration/test_file_df_writer_integration/test_common_file_df_writer_integration.py
tests/tests_unit/test_file/test_file_df_writer_unit.py

Make default value of `FileDFWriter.Options(if_exists=...)` consistent with DB connections, which use `APPEND`.

[DOP-23979] Change default FileDFWriter.Options(if_exists) to APPEND

---

docs/changelog/next_release/342.bugfix.rst
onetl/_util/spark.py
tests/fixtures/spark_mock.py
tests/tests_unit/test_db/test_db_reader_unit/test_greenplum_reader_unit.py
tests/tests_unit/test_db/test_db_writer_unit/test_greenplum_writer_unit.py

Java's `Runtime.availableProcessors()` return number of _available_ processors in the system, but starting Spark session with `master=local[N]` applies the hard limit for the number of executor threads. So even if system has a lot of processor cores available, only some of them will be used by Spark.
This lead to showing a warning that the number of Greenplum connections is high even if Spark session was started with `master=local[1]` or `master=local[10]` (max 10 executors, so max 10 connections to GP, warning threshold is 30).
Fixed, added a bunch of unit tests, using mocks to cover different cases (master=local, master=yarn with static allocation, master=yarn with dynamic allocation).
(see [CONTRIBUTING.rst](https://github.com/MobileTeleSystems/onetl/blob/develop/CONTRIBUTING.rst) for …

[DOP-23969] Fix Greenplum parallel connections warning for master=local[N]

---

docs/changelog/next_release/345.dependency.rst
docs/connection/db_connection/mongodb/types.rst
onetl/connection/db_connection/clickhouse/connection.py
onetl/connection/db_connection/mongodb/connection.py
onetl/connection/db_connection/mysql/connection.py
onetl/connection/db_connection/oracle/connection.py
onetl/connection/db_connection/postgres/connection.py
tests/tests_unit/tests_db_connection_unit/test_clickhouse_unit.py
tests/tests_unit/tests_db_connection_unit/test_mongodb_unit.py
tests/tests_unit/tests_db_connection_unit/test_mysql_unit.py
tests/tests_unit/tests_db_connection_unit/test_oracle_unit.py
tests/tests_unit/tests_db_connection_unit/test_postgres_unit.py

Use latest version for JDBC drivers & MongoDB. For Clickhouse, latest version is actually 0.8.1, but driver was changed significantly in 0.8.x, and may be unstable, so skipping it for now.

[DOP-23983] Update JDBC drivers to latest versions

---

docs/changelog/next_release/346.feature.rst
onetl/connection/db_connection/greenplum/connection.py
onetl/connection/db_connection/hive/connection.py
onetl/connection/db_connection/jdbc_connection/connection.py
onetl/connection/db_connection/jdbc_mixin/connection.py
onetl/connection/db_connection/kafka/connection.py
onetl/connection/db_connection/mongodb/connection.py
onetl/connection/file_df_connection/spark_file_df_connection.py
onetl/db/db_reader/db_reader.py
onetl/db/db_writer/db_writer.py
onetl/file/file_df_reader/file_df_reader.py
onetl/file/file_df_writer/file_df_writer.py
tests/tests_integration/test_metrics/test_spark_metrics_recorder_postgres.py
tests/tests_integration/tests_db_connection_integration/test_oracle_integration.py
tests/tests_integration/tests_db_connection_integration/test_teradata_integration.py

Now all `DB.check()` methods ping database both from Spark driver and at least one Spark executor, to be sure that next operations (e.g. check+write) will not fail on executor side.

[DOP-22425] Run DB.check() on both driver and executor

---

docs/changelog/next_release/339.feature.rst
onetl/connection/db_connection/mongodb/connection.py

According to MongoDB Spark connector documentation, it is possible to pass `comment` option describing current operation, and it will be saved to some internal profiling collection for later analysis.
Now passing `client_info` to this field. It is supported only for MongoDB server 4.4+, so added a server version check as well.
I've tried to get this internal collection content, but it is always empty for some reason. So no tests for now.

[DOP-22428] Send client_info for MongoDB

---

docs/changelog/next_release/350.bugfix.rst
onetl/connection/db_connection/hive/connection.py
tests/tests_integration/tests_core_integration/tests_db_writer_integration/test_hive_writer_integration.py

For Hive, table names `somedb.sometable` and `SOMEDB.SOMETABLE` are exactly the same, because it is case insensitive. But for `DBWriter(Hive)` it was not, and writing data to existing table with different case lead to recreating the entire table, even if user passed `Hive.WriteOptions(if_exists="append")`

[DOP-24322] Properly handle different table name cases in DBWriter(Hive)

---

onetl/hwm/auto_hwm.py

Added a stub for `reset()` method in `AutoDetectHWM` since `HWM` now has an abstract `reset()` method  

Add AutoDetectHWM.reset

---

docs/file_df/file_formats/xml.rst
onetl/file/format/__init__.py
onetl/file/format/file_format.py
onetl/file/format/xml.py
setup.cfg
tests/tests_integration/test_file_format_integration/test_xml_integration.py
tests/tests_unit/test_file/test_format_unit/test_xml_unit.py

Previously XML class documentation only noted that options are documented elsewhere. Now all of them are documented, included to constructor signature and can be recommended by IDE.
Before:
https://onetl.readthedocs.io/en/0.13.3/file_df/file_formats/xml.html
After:
https://onetl--355.org.readthedocs.build/en/355/file_df/file_formats/xml.html

[DOP-22430] Improve XML documentation

---

docs/file_df/file_formats/csv.rst
onetl/file/format/csv.py
onetl/file/format/file_format.py
setup.cfg
tests/tests_integration/test_file_format_integration/test_csv_integration.py
tests/tests_unit/test_file/test_format_unit/test_csv_unit.py

Previously CSV class documentation only noted that options are documented elsewhere. Now all of them are documented, included to constructor signature and can be recommended by IDE.
Before:
https://onetl.readthedocs.io/en/0.13.3/file_df/file_formats/csv.html
After:
https://onetl--358.org.readthedocs.build/en/358/file_df/file_formats/csv.html

[DOP-22432] Improve CSV documentation

---

docs/file_df/file_formats/json.rst
docs/file_df/file_formats/jsonline.rst
onetl/file/format/file_format.py
onetl/file/format/json.py
onetl/file/format/jsonline.py
setup.cfg
tests/tests_integration/test_file_format_integration/test_json_integration.py
tests/tests_unit/test_file/test_format_unit/test_json_unit.py
tests/tests_unit/test_file/test_format_unit/test_jsonline_unit.py

Previously JSON and JSONLine classes documentation only noted that options are documented elsewhere. Now all of them are documented, included to constructor signature and can be recommended by IDE.
Before:
https://onetl.readthedocs.io/en/0.13.3/file_df/file_formats/json.html
https://onetl.readthedocs.io/en/0.13.3/file_df/file_formats/jsonline.html
After:
https://onetl--359.org.readthedocs.build/en/359/file_df/file_formats/json.html
https://onetl--359.org.readthedocs.build/en/359/file_df/file_formats/jsonline.html

[DOP-22433] Improve JSON/JSONLine documentation

---

docs/file_df/file_formats/orc.rst
onetl/connection/db_connection/hive/connection.py
onetl/file/format/orc.py
tests/tests_unit/test_file/test_format_unit/test_orc_unit.py

Previously ORC class documentation only noted that options are documented elsewhere. Now all of them are documented, included to constructor signature and can be recommended by IDE.
Before:
https://onetl.readthedocs.io/en/0.13.3/file_df/file_formats/orc.html
After:
https://onetl--362.org.readthedocs.build/en/362/file_df/file_formats/orc.html

[DOP-22434] Improve ORC documentation

---

docs/file_df/file_formats/parquet.rst
onetl/connection/db_connection/hive/connection.py
onetl/file/format/parquet.py
tests/tests_unit/test_file/test_format_unit/test_parquet_unit.py

Previously Parquet class documentation only noted that options are documented elsewhere. Now all of them are documented, included to constructor signature and can be recommended by IDE.
Before:
https://onetl.readthedocs.io/en/0.13.3/file_df/file_formats/parquet.html
After:
https://onetl--361.org.readthedocs.build/en/361/file_df/file_formats/parquet.html

[DOP-22434] Improve Parquet documentation

---

.github/workflows/data/s3/matrix.yml
docs/changelog/next_release/379.feature.rst
onetl/connection/file_connection/file_connection.py
onetl/connection/file_connection/s3.py
onetl/connection/file_connection/webdav.py
tests/tests_integration/tests_core_integration/test_file_downloader_integration.py
tests/tests_integration/tests_core_integration/test_file_mover_integration.py
tests/tests_integration/tests_file_connection_integration/test_s3_file_connection_integration.py

Spark 4.0 started to create empty objects in S3 with name ending with `/` as a directory-like marker. This implementation avoids scanning all paths by prefix, and just fetching object by key instead, which is much faster. This is also the case for Iceberg.
Adjust S3 connector `_scan_entries` and `_remove_dir` code to handle this case.

Treat S3 objects with name ending with slash as directory marker

---

docs/changelog/next_release/380.improvement.rst
onetl/connection/file_connection/file_connection.py
onetl/connection/file_connection/s3.py
onetl/connection/file_connection/samba.py

S3 and Samba protocols allow bulk files removal (using list of objects and wildcard pattern respectively). Let's use them to speed up `remove_dir(recursive=True)`.

Speed up remove_dir_recursive

---

README.rst
docs/changelog/next_release/392.feature.rst
docs/connection/file_df_connection/spark_s3/prerequisites.rst
docs/connection/file_df_connection/spark_s3/troubleshooting.rst
onetl/connection/file_df_connection/spark_s3/connection.py
tests/fixtures/connections/s3.py
tests/tests_integration/test_file_df_connection_integration/test_spark_s3_integration.py
tests/tests_unit/tests_file_df_connection_unit/test_spark_s3_unit.py

Allowed to set ``path_style_access`` as a parameter in ``SparkS3`` connection instead of using ``extra`` field:
```python
SparkS3(
...,
path_style_access=True,
)
```
This change improved IDE autocompletion and made it more explicit that the parameter is important for the connector's functionality.

[DOP-28400] Move path_style_access from SparkS3.extra
